### PR TITLE
Minor change to support obfuscation utilities.

### PR DESCRIPTION
**Pull request by SyntaxPolice**
@scottyab Can you take a look at this and let me know if this simple change addresses the obfuscation issue you filed some months back? Sorry I haven't addressed your PRs. I do appreciate them.

### CODE REVIEW

**Comment by SyntaxPolice** [comment]
Thank you very much, @ashughes. How's this look?

**Comment by ashughes** [comment]
That looks correct to me. However I think using `getName()` for both would be better since it uses the fully qualified class name (package + name). It's not what the code was doing before though.

**Comment by ericmann** [comment]
@SyntaxPolice Can you please update the PR to fix the merge conflict?

**Comment by kassim** [comment]
wouldn't `getClass() == LinuxPRNGSecureRandomProvider.class` suffice?
pretty sure they're single instance

**Pull request closed without merging**
