### PR TITLE
Support obfuscation of PrngFixes inner classes

### PR DESCRIPTION
**Pull request by scottyab**
Changed the equals check to use LinuxPRNGSecureRandomProvider.class.getSimpleName() rather than "LinuxPRNGSecureRandomProvider". This way it doesn't matter if proguard (or whatever) changes the class name. Related to scottyab/secure-preferences#31

Includes @cermak's PR to Add iteration count to generateKeyFromPassword method.

### CODE REVIEW

**Comment by kassim** [comment]
I too ran into this issue. I can confirm that the solution works (simply referencing the class rather than the string), though perhaps the PR is changing too much (should only be 3 lines of code really).

**Comment by Pedramrn** [comment]
Same issue with proguard, the cause is the hard coded class name. I confirm this commit 630b85 resolves this issue.

**Comment by SyntaxPolice** [comment]
Thanks. Can you check this branch? I'm trying to make this a minimal
change: https://github.com/tozny/java-aes-crypto/pull/24

If you want to try out the getName thing and submit a modification like
that, it would be very helpful!

**Comment by ericmann** [comment]
Closing in favor of #24.

**Pull request closed without merging**
