### PR TITLE
#35 jdk example, the test pass, but 

### PR DESCRIPTION
**Pull request by spyhunter99**
i have no idea if this is considered secure or not, use at your own risk.

### CODE REVIEW

**Comment by spyhunter99** [comment]
fixed the merge conflict and updated against master (mostly javadoc changes)
the biggest deltas with this branch

 - obviously anything android isn't included in the jre module
 - the open ssl fix is commented out, this is the only part i'm not sure of
 - generate seed doesn't have pid's attached to it

**Comment by spyhunter99** [comment]
any particular reason this was closed?

**Comment by galxy25** [comment]
> any particular reason this was closed?

"i have no idea if this is considered secure or not, use at your own risk."

We have decided to not use it.

**Comment by spyhunter99** [comment]
is it insecure?

**Comment by galxy25** [comment]
> is it insecure?
> […](#)

We don't have the bandwidth to make that determination at this time.

**Pull request closed without merging**
